/* DATA MANIPULATION FUNCTIONS */
/* string manipulations 
    More string functions: https://www.w3schools.com/sql/sql_ref_sqlserver.asp  */
SELECT UPPER(firstName) AS upperName
SELECT LOWER(firstName) AS lowerName
FROM Employees

SELECT LTRIM(firstName) AS cleanFirstName -- remove spaces on the left
SELECT RTRIM(firstName) AS cleanFirstName -- remove spaces on the right
SELECT TRIM(firstName) AS cleanFirstName  -- remove any space from right or left
FROM Employees


/* date manipulation 
    More date functions: https://www.w3schools.com/sql/sql_ref_sqlserver.asp  */
SELECT 
    from_date,
    YEAR(from_date) AS year,
    MONTH(from_date) AS month,
    DAY(from_date) AS day,
    DATE_FORMAT(from_date, '%d.%m.%y') AS new_format
FROM Calendar


/* Numeric manipulation 
    More numeric functions: https://www.w3schools.com/sql/sql_ref_sqlserver.asp  */
SELECT voltage, resistance, voltage / resistance AS current
FROM tableName

SELECT 
    variance,
    SQRT(variance) AS std
FROM NumValues

/*  Aggregate functions 
    More functions: https://www.w3schools.com/sql/sql_ref_sqlserver.asp  
    Note that Aggregate functions migth require GROUP BY  */
SELECT
    MIN(amount) AS smallest_order, -- MIN over a whole column
    MAX(amount) AS largest_order   -- MAX over a whole column
FROM Orders;

SELECT
    customer_id,
    SUM(amount) AS total_amount   -- SUM is applied to each aggregated group generated by GROUP BY
FROM Orders
GROUP BY customer_id;

SELECT 
    customer_id,
    AVG(amount) AS mean_amount -- AVG is applied to each aggregated group generated by GROUP BY
FROM Orders
GROUP BY customer_id
HAVING AVG(amount) > 150; -- HAVING is used to filter among the groups after aggregation

/* Note that when using GROUP BY each selected column must either be born from the aggregation or given to GROUP BY 
SELECT
    customer_id,
    order_id,
    SUM(amount) AS total_amount
FROM orders
GROUP BY customer_id; 

This is bad as there might be multiple order_id within each group  */

